#include "alpaca.h"

const stm32_pin_info PIN_MAP[]={
{ GPIOA,  0 },
{ GPIOA,  1 },
{ GPIOA,  2 },
{ GPIOA,  3 },
{ GPIOA,  4 },
{ GPIOA,  5 },
{ GPIOA,  6 },
{ GPIOA,  7 },
{ GPIOA,  8 },
{ GPIOA,  9 },
{ GPIOA,  10},
{ GPIOA,  11},
{ GPIOA,  12},
{ GPIOA,  13},
{ GPIOA,  14},
{ GPIOA,  15},
{ GPIOB,  0 },
{ GPIOB,  1 },
{ GPIOB,  2 },
{ GPIOB,  3 },
{ GPIOB,  4 },
{ GPIOB,  5 },
{ GPIOB,  6 },
{ GPIOB,  7 },
{ GPIOB,  8 },
{ GPIOB,  9 },
{ GPIOB,  10},
{ GPIOB,  11},
{ GPIOB,  12},
{ GPIOB,  13},
{ GPIOB,  14},
{ GPIOB,  15},
{ GPIOC,  0 },
{ GPIOC,  1 },
{ GPIOC,  2 },
{ GPIOC,  3 },
{ GPIOC,  4 },
{ GPIOC,  5 },
{ GPIOC,  6 },
{ GPIOC,  7 },
{ GPIOC,  8 },
{ GPIOC,  9 },
{ GPIOC,  10},
{ GPIOC,  11},
{ GPIOC,  12},
{ GPIOC,  13},
{ GPIOC,  14},
{ GPIOC,  15},
{ GPIOD,  0 },
{ GPIOD,  1 },
{ GPIOD,  2 },
{ GPIOD,  3 },
{ GPIOD,  4 },
{ GPIOD,  5 },
{ GPIOD,  6 },
{ GPIOD,  7 },
{ GPIOD,  8 },
{ GPIOD,  9 },
{ GPIOD,  10},
{ GPIOD,  11},
{ GPIOD,  12},
{ GPIOD,  13},
{ GPIOD,  14},
{ GPIOD,  15},
{ GPIOE,  0 },
{ GPIOE,  1 },
{ GPIOE,  2 },
{ GPIOE,  3 },
{ GPIOE,  4 },
{ GPIOE,  5 },
{ GPIOE,  6 },
{ GPIOE,  7 },
{ GPIOE,  8 },
{ GPIOE,  9 },
{ GPIOE,  10},
{ GPIOE,  11},
{ GPIOE,  12},
{ GPIOE,  13},
{ GPIOE,  14},
{ GPIOE,  15},
{ GPIOF,  0 },
{ GPIOF,  1 },
{ GPIOF,  2 },
{ GPIOF,  3 },
{ GPIOF,  4 },
{ GPIOF,  5 },
{ GPIOF,  6 },
{ GPIOF,  7 },
{ GPIOF,  8 },
{ GPIOF,  9 },
{ GPIOF,  10},
{ GPIOF,  11},
{ GPIOF,  12},
{ GPIOF,  13},
{ GPIOF,  14},
{ GPIOF,  15},
{ GPIOG,  0 },
{ GPIOG,  1 },
{ GPIOG,  2 },
{ GPIOG,  3 },
{ GPIOG,  4 },
{ GPIOG,  5 },
{ GPIOG,  6 },
{ GPIOG,  7 },
{ GPIOG,  8 },
{ GPIOG,  9 },
{ GPIOG,  10},
{ GPIOG,  11},
{ GPIOG,  12},
{ GPIOG,  13},
{ GPIOG,  14},
{ GPIOG,  15},
{ GPIOH,  0 },
{ GPIOH,  1 },
};	

 
